apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: cluster-issuer
spec:
  acme:
    server: https://acme-v02.api.letsencrypt.org/directory
    email: alexander@hyll.nu
    privateKeySecretRef:
      name: cluster-issuer-account-key
    solvers:
    - http01:
        ingress:
          class: nginx
          ingressTemplate:
            metadata:
              annotations:
                kubernetes.io/ingress.allow-http: "true"
                ingress.kubernetes.io/ssl-redirect: "false"
                nginx.org/redirect-to-https: "false"