apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
metadata:
  name: arbitrary
resources:
#- issuer.yaml
# Backend
- back/backend.yaml
- back/deployment.yaml
- back/service.yaml
- back/ingress.yaml
# Frontend
- front/backend.yaml
- front/deployment.yaml
- front/service.yaml
- front/ingress.yaml
