apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- cluster-issuer.yml
# Backend
- back/frontend-config.yml
- back/backend.yml
- back/deployment.yml
- back/service.yml
- back/ingress.yml
# Frontend
- front/frontend-config.yml
- front/backend.yml
- front/deployment.yml
- front/service.yml
- front/ingress.yml
# Postgres
- postgres/configmap.yml
- postgres/storageclass.yml
- postgres/pvc.yml
- postgres/deployment.yml
- postgres/service.yml
# Hedge Nordic Scraper
- hedge-nordic-scraper/cronjob.yml
