apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
metadata:
  name: arbitrary
resources:
- cluster-issuer.yaml
# Backend
- back/frontend-config.yml
- back/backend.yml
- back/deployment.yml
- back/service.yml
- back/ingress.yml
# Frontend
- front/frontend-config.yml
- front/backend.yml
- front/deployment.yml
- front/service.yml
- front/ingress.yml
