apiVersion: cloud.google.com/v1
kind: BackendConfig
metadata:
  name: portfolio-backendconfig
  namespace: portfolio
  labels:
    app: portfolio
spec:
  healthCheck:
    checkIntervalSec: 30
    timeoutSec: 30
    healthyThreshold: 2
    unhealthyThreshold: 10
    type: "HTTP"
    requestPath: /
