apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  annotations:
    cert-manager.io/cluster-issuer: cluster-issuer
    acme.cert-manager.io/http01-edit-in-place: "true"
    kubernetes.io/ingress.global-static-ip-name: portfolio-ip
    networking.gke.io/v1beta1.FrontendConfig: portfolio-frontend-config
  name: portfolio-ingress
  namespace: portfolio
  labels:
    app: portfolio
spec:
  tls:
  - hosts:
    - alexander.hyll.nu
    secretName: portfolio-cert
  rules:
  - host: alexander.hyll.nu
    http:
      paths:
      - pathType: Prefix
        path: /
        backend:
          service:
            name: portfolio-service
            port:
              number: 80