apiVersion: apps/v1
kind: Deployment # Create a deployment
metadata:
  namespace: portfolio
  name: postgres # Set the name of the deployment
spec:
  strategy:
   rollingUpdate:
     maxSurge: 1
     maxUnavailable: 1
   type: RollingUpdate
  replicas: 1 # Only 1 replica per volume claim (!)
  selector:
    matchLabels:
      app: postgres
  template:
    metadata:
      namespace: portfolio
      labels:
        app: postgres
    spec:
      containers:
        - name: postgres
          image: postgres:12.10 # Docker image
          resources:
            limits:
              cpu: ".5"
              memory: "600Mi"
            requests:
              cpu: ".250"
              memory: "600Mi"
          imagePullPolicy: "IfNotPresent"
          ports:
            - containerPort: 5432 # Exposing the container port 5432 for PostgreSQL client connections.
          envFrom:
            - configMapRef:
                name: postgres-secret # Using the ConfigMap postgres-secret
          volumeMounts:
            - mountPath: /var/lib/postgresql/data
              name: postgresdata
      volumes:
        - name: postgresdata
          persistentVolumeClaim:
            claimName: postgresql-pv
