kind: PersistentVolumeClaim  # Create PVC
apiVersion: v1
metadata:
  namespace: portfolio
  name: postgresql-pv
spec:
  storageClassName: pg-storage-class  # StorageClassName
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 200Gi
