kind: StorageClass
apiVersion: storage.k8s.io/v1
metadata:
  namespace: portfolio
  name: pg-storage-class
provisioner: kubernetes.io/gce-pd
parameters:
  type: pd-standard
  replication-type: regional-pd
allowVolumeExpansion: true
allowedTopologies:
  - matchLabelExpressions:
      - key: failure-domain.beta.kubernetes.io/zone
        values:
          - europe-north1-a
          - europe-north1-c
