kind: StorageClass
apiVersion: storage.k8s.io/v1
metadata:
  name: pg-storage-class
provisioner: kubernetes.io/gce-pd
parameters:
  type: pd-standard
  replication-type: regional-pd
allowedTopologies:
  - matchLabelExpressions:
      - key: failure-domain.beta.kubernetes.io/zone
        values:
          - europe-west1-a
          - europe-west1-c
